version: '3'
services: 
    app: 
        image: node:16
        volumes: 
            - './:/workspace'
            - 'node_modules:/workspace/node_modules'
        working_dir: /workspace
        command: tail -f /dev/null

volumes: 
    node_modules: